#!/bin/bash
sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
sudo yum install -y docker-ce
sudo usermod -aG docker $USER 
sudo systemctl enable docker
sudo systemctl start docker
