tosca_definitions_version: cloudify_dsl_1_2

imports:
  - http://www.getcloudify.org/spec/cloudify/3.3m6/types.yaml

inputs:

  aws_access_key_id:
    type: string
    default: ''

  aws_secret_access_key:
    type: string
    default: ''

  agent_security_group_name:
    type: string

  agent_keypair_name:
    type: string

  agents_user:
    type: string
    default: centos


node_templates:

  configuration:
    type: cloudify.nodes.Root
    interfaces:
      cloudify.interfaces.lifecycle:
        configure:
          implementation: scripts/configure.py
          executor: central_deployment_agent
          inputs:
            aws_access_key_id: { get_input: aws_access_key_id }
            aws_secret_access_key: { get_input: aws_secret_access_key }
            agent_security_group_name: { get_input: agent_security_group_name }
            agent_keypair_name: { get_input: agent_keypair_name }
            agents_user: { get_input: agents_user }
