tosca_definitions_version: cloudify_dsl_1_2

imports:
  - http://www.getcloudify.org/spec/cloudify/3.4m5/types.yaml
  - dependencies/vsphere_dependencies.yaml

inputs:

  user_ssh_key:
    type: string
    default: ''
    description: >
      SSH key to authorize for access to the image builder user account.

  agents_keypair_name:
    type: string
    default: cloudify-agents-keypair
    description: >
      Keypair to be generated and used for accessing agents on VMs.

  agents_user:
    type: string
    default: centos
    description: >
      User to be used for accessing agents on VMs.

  vsphere_username:
    type: string
    description: >
      Username used to connect to vCenter.

  vsphere_password:
    type: string
    description: >
      Password used to connect to vCenter.

  vsphere_host:
    type: string
    description: >
      IP or resolvable hostname of vCenter server.

  vsphere_port:
    type: integer
    default: 443
    description: >
      Port of vCenter server.

  vsphere_datacenter_name:
    type: string
    description: >
      Datacenter to use on vCenter.

  vsphere_resource_pool_name:
    type: string
    default: Resources
    description: >
      Resource pool to use on vCenter.

  vsphere_auto_placement:
    type: boolean
    default: true
    description: >
      Whether to use vCenter's auto-placement algorithms
      or this plugin's.




node_templates:

  general_configuration:
    type: cloudify.nodes.Root
    interfaces:
      cloudify.interfaces.lifecycle:
        configure:
          implementation: scripts/configure.py
          executor: central_deployment_agent
          inputs:
            user_ssh_key: { get_input: user_ssh_key }

  vsphere_configuration:
    type: cloudify.nodes.Root
    interfaces:
      cloudify.interfaces.lifecycle:
        configure:
          implementation: scripts/configure_vsphere.py
          executor: central_deployment_agent
          inputs:
            agents_keypair_name: { get_input: agents_keypair_name }
            agents_user: { get_input: agents_user }
            vsphere_username: { get_input: vsphere_username }
            vsphere_password: { get_input: vsphere_password }
            vsphere_host: { get_input: vsphere_host }
            vsphere_port: { get_input: vsphere_port }
            vsphere_datacenter_name: { get_input: vsphere_datacenter_name }
            vsphere_resource_pool_name: { get_input: vsphere_resource_pool_name }
            vsphere_auto_placement: { get_input: vsphere_auto_placement }

  # This is a workaround for cloudify not installing the required dependencies without a node that 'uses' them
  dependencies_install:
    type: cloudify.vsphere_dependencies.Install

outputs:
  agents_public_key:
    value: { get_attribute: [vsphere_configuration, agents_public_key] }
