#!/usr/bin/env bash
set -e

# disable selinux
sudo setenforce 0
sudo sed -ri 's/SELINUX=.+/SELINUX=disabled/' /etc/selinux/config

# Disable requiretty for future fabric calls
sudo sed -i -e 's/^Defaults.*requiretty/# Defaults requiretty/g' /etc/sudoers

sudo hostnamectl set-hostname cloudify