#!/bin/bash
set -e

INSTALL_RPM="cloudify-manager-install.rpm"
CONFIG_FILE_PATH="/etc/cloudify/config.yaml"


function install_rpm
{
  echo "Downloading Cloudify's install RPM from: ${INSTALL_RPM_URL}"
  curl ${INSTALL_RPM_URL} -o ${INSTALL_RPM} -s

  echo "Installing RPM..."
  sudo rpm -i ${INSTALL_RPM}

  rm ${INSTALL_RPM}
}

function generate_keys
{
  # generate public/private key pair and add to authorized_keys
  ssh-keygen -t rsa -f ~/.ssh/id_rsa -q -N ''
  cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
}


function install_manager_packages
{
  echo "Installing Cloudify Manager..."

  # bootstrap the manager locally
  yum install -y /opt/cloudify/sources/*.rpm
}

install_rpm
install_manager_packages
generate_keys
