#! /usr/bin/env bash
set -e

# Install the appropriate dependencies into the mgmtworker env
if [[ -f /tmp/dependencies/${PACKER_BUILD_NAME}_dependencies.tar.gz ]]; then
  sudo /opt/mgmtworker/env/bin/pip install /tmp/dependencies/${PACKER_BUILD_NAME}_dependencies.tar.gz
fi

# Clean up
rm -rf /tmp/dependencies
