#! /usr/bin/env bash
set -e


# Install the appropriate dependencies into the mgmtworker env
if [[ -f /tmp/dependencies/${PACKER_BUILD_NAME}_dependencies.zip ]]; then

  if [ "$PACKER_BUILD_NAME" == "azure" ]; then
    sudo yum -y install libffi-devel openssl-devel
  fi

  sudo yum -y install gcc libffi-devel python-devel openssl-devel
  sudo /opt/mgmtworker/env/bin/pip install /tmp/dependencies/${PACKER_BUILD_NAME}_dependencies.zip

fi
