#! /usr/bin/env bash
set -e

# Security enabled, activate the cron job
sudo mv /tmp/cloudify_security_reconfiguration /opt/cloudify_security_reconfiguration
sudo chown root. /opt/cloudify_security_reconfiguration
sudo chmod 500 /opt/cloudify_security_reconfiguration

sudo mv /tmp/cloudify_security_reconfiguration.cron /etc/cron.d/cloudify_security_reconfiguration
sudo chown root. /etc/cron.d/cloudify_security_reconfiguration
sudo chmod 440 /etc/cron.d/cloudify_security_reconfiguration
