#! /usr/bin/env bash
set -e

CFY_BIN="cfy"
cd ${BLUEPRINT_PATH}

# Inject the correct username
sudo sed -i "s/<<IMAGEBUILDERUSER>>/$(whoami)/" scripts/configure.py

BLUEPRINT_FILENAME=${BLUEPRINT_FILE_NAME_PREFIX}_${PACKER_BUILD_NAME}

${CFY_BIN} profile use 127.0.0.1

${CFY_BIN} blueprints upload ${BLUEPRINT_FILENAME}.yaml -b ${BLUEPRINT_NAME}
