#! /usr/bin/env bash
ip=$(get_first_external_ip)

/usr/bin/sed -i -e "s/MANAGEMENT_IP=.*/MANAGEMENT_IP="'"'"${ip}"'"'"/" /etc/sysconfig/cloudify-mgmtworker
/usr/bin/sed -i -e "s/AMQP_HOST=.*/AMQP_HOST="'"'"${ip}"'"'"/" /etc/sysconfig/cloudify-amqpinflux
/usr/bin/sed -i -e "s/INFLUXDB_HOST=.*/INFLUXDB_HOST="'"'"${ip}"'"'"/" /etc/sysconfig/cloudify-amqpinflux
/usr/bin/sed -i -e "s/RABBITMQ_HOST=.*/RABBITMQ_HOST="'"'"${ip}"'"'"/" /etc/sysconfig/cloudify-riemann
/usr/bin/sed -i -e "s/MANAGEMENT_IP=.*/MANAGEMENT_IP="'"'"${ip}"'"'"/" /etc/sysconfig/cloudify-riemann
/usr/bin/sed -i -e "s/RABBITMQ_HOST=.*/RABBITMQ_HOST="'"'"${ip}"'"'"/" /etc/sysconfig/cloudify-riemann
/usr/bin/sed -i -e "s#MANAGER_FILE_SERVER_URL="'"'"http://.*:53229"'"'"#MANAGER_FILE_SERVER_URL="'"'"http://${ip}:53229"'"'"#" /etc/sysconfig/cloudify-mgmtworker
/usr/bin/sed -i -e "s#MANAGER_FILE_SERVER_BLUEPRINTS_ROOT_URL="'"'"http://.*:53229/blueprints"'"'"#MANAGER_FILE_SERVER_BLUEPRINTS_ROOT_URL="'"'"http://${ip}:53229/blueprints"'"'"#" /etc/sysconfig/cloudify-mgmtworker
/usr/bin/sed -i -e "s/host => "'"'".*"'"'"/host => "'"'"${ip}"'"'"/" /etc/logstash/conf.d/logstash.conf
/usr/bin/sed -i -e "s/db_address: "'"'".*"'"'"/db_address: "'"'"${ip}"'"'"/" /opt/manager/cloudify-rest.conf
/usr/bin/sed -i -e "s#amqp_address: "'"'".*:5672/"'"'"#amqp_address: "'"'"${ip}:5672/"'"'"#" /opt/manager/cloudify-rest.conf
/usr/bin/sed -i -e "s/"'"'"host"'"'": "'"'".*"'"'"/"'"'"host"'"'": "'"'"${ip}"'"'"/" /opt/cloudify-ui/backend/gsPresets.json
/usr/bin/sed -i -e "s/"'"'"broker_hostname"'"'": "'"'".*"'"'"/"'"'"broker_hostname"'"'": "'"'"${ip}"'"'"/" /opt/mgmtworker/work/broker_config.json
